version: '3.4'

services:
  coze-discord-proxy:
    image: deanxv/coze-discord-proxy:latest
    container_name: coze-discord-proxy
    restart: always
    ports:
      - "7077:7077"
    volumes:
      - ./data:/app/coze-discord-proxy/data
    environment:
      - BOT_TOKEN=OTEwMzU2OTE1MjYxOTM5Nzgy.GEK6T_.Ybkp3xxE5BCDJ1rhtNAgxvc2-zTmS7wjrsSNg0  # 必须修改为我们主动发送消息的Bot-Token
      - GUILD_ID=1231581209407000687  # 必须修改为两个机器人所在的服务器ID
      - COZE_BOT_ID=1231581385056063580  # 必须修改为由coze托管的机器人ID
      - CHANNEL_ID=1231581209407000691  # 默认频道-在使用与openai对齐的接口时(/v1/chat/completions) 消息会默认发送到此频道
      - PROXY_SECRET=123456  # [可选]修改此行为请求头校验的值（前后端统一）
      - TZ=Asia/Shanghai
